from .revisar_equipos import *
from .compras import *
from .equipos import *
from .legalizador import *
from .portas import *
from .preactivador import *
from .consulta_seriales import *
from .consulta_seriales2 import *
from .legalizador_simcard import *
from .inventario_postpago import *
from .actualizar_precios import *
from .recargas import *
from .logo import *
from .volantes import *
